import React from 'react';
import IngredientIndexItem from './ingredient/ingredient_index_item';

class RecipeShow extends React.Component{

  componentDidMount(){
    this.props.fetchRecipe(this.props.match.params.recipeId);
    // debugger
    this.props.fetchIngredients();
  }
  render(){
    // debugger
    const { recipe, ingredients } = this.props;

    const recipeHead  = (
      <div className="recipe-show">
        <div className="post-head-container">
          <a className="theme unhealthy subheading">
            Unhealthyish
            {/* replace with tagging with ord1 */}
          </a>
          <h1 className="title">{recipe.title}</h1>
          <div className="author">
            <br />
            <p> Author ID: {recipe.user_id}</p>
          </div>
          <div className="rating subheading">
            12 ratings *****
          </div>
        </div>
        <div className="main-image">
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          PIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZAPIZZA
          </div>
        <div className="description header">
          <div className="body">
            {recipe.body}
          </div>
        </div>
      </div>
    );

    const recipeIngredients = (
      <div className="ingredients-container">
        <div>
          <ul>{
            ingredients.map(ingredient => (
              <IngredientIndexItem
              key = {ingredient.id}
              ingredient = {ingredient}
              />              
            ))
          }
          </ul>
        </div>
      </div>
    );
    
    const recipePage = (
      <div className="recipe-page">
        { recipeHead }
        { recipeIngredients }
      </div>
    );
    return(
      recipePage
    );
  }
}

RecipeShow.defaultProps = {
  recipe:{
    title: "Beep.",
    user_id: "Bop",
    body: "Boop."
  },
  ingredients:{
    text: "Beep.",
    recipe_id: "Bop.",
    ord: "Boop."
  }
}

export default RecipeShow;